// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVjlLMOLPiyA3Hb61pGzBpyoaIxxrP70g',
    appId: '1:88966980004:web:e44dd59ab5ea14ba97a131',
    messagingSenderId: '88966980004',
    projectId: 'logisticx-5e833',
    authDomain: 'logisticx-5e833.firebaseapp.com',
    storageBucket: 'logisticx-5e833.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFjmcBBguHNhl33bqmXhvse4DNpSYSrZM',
    appId: '1:88966980004:android:4d7e4662cea3569b97a131',
    messagingSenderId: '88966980004',
    projectId: 'logisticx-5e833',
    storageBucket: 'logisticx-5e833.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiSM_2UtO4CmuoUzogbR3T8XyOTD9HghA',
    appId: '1:88966980004:ios:beec5be26d4a90c497a131',
    messagingSenderId: '88966980004',
    projectId: 'logisticx-5e833',
    storageBucket: 'logisticx-5e833.appspot.com',
    iosClientId:
        '88966980004-np4ukol02s567b7lelt79nsu6l45rt2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.logisticxDatn',
  );
}
